# --- Basic options --- #

# Name of website
title: é²¸ææ•°æ®
# Short description of your site
description: å…³æ³¨é²¸æï¼Œç»™ä½ æƒŠå–œï¼

# Your name to show in the footer
author: Whalysis

# --- List of links in the navigation bar --- #

navbar-links:
    
#  ğŸ‘‰å…³äºé²¸æğŸ‹: "aboutme"
  # remember to unlock it if needed
#  Resume:
#   - English_Resume: 'e_cv'
#    - Chinese_Resume: 'c_cv'

#   é²¸æ:
#     - é²¸æé¡¹ç›®: 
#     - Pythonå­¦ä¹ :
#     - Rå­¦ä¹ :
#     - æ•°æ®åˆ†æ:
#     - ç»Ÿè®¡:
    
    
#   DATA3888: 
#     - Week1 KNN & CV: 'DATA3888_2021_Week1_cv'
#     - Week1 Clustering: 'DATA3888_2021_Week1_clustering'

#   æ•°æ®åº“: 
#     - ç®€å•: "sql"
#     - ä¸­ç­‰: "sql_medium"

  ğŸ‘‰é²¸é²¸å°ç­è¯¾ğŸ‹: 
    - æ•°æ®ç§‘å­¦é¡¹ç›®èƒŒæ™¯æå‡è¯¾: "https://www.offerrealize.com/plan#dsproject"
    - æ•°æ®ç§‘å­¦é¢è¯•è¾…å¯¼è¯¾: "https://www.offerrealize.com/plan#ds"
#   ğŸ‘‰å®æˆ˜é¡¹ç›®ğŸ‹:
#       - è½¦é™©é¢„æµ‹: "projects/safe_driver_prediction"
#   ğŸ‘‰SQLé¢ç»ğŸ’¯:
#     - çª—å£å‡½æ•°: "SQL/window"
#     - CTE: "SQL/cte"
#     - å­æŸ¥è¯¢: "SQL/subquery"
#     - æ¡ä»¶åˆ¤æ–­: "SQL/casewhen"
#     - è¡¨æ ¼è¿æ¥: "SQL/join"
#     - è‡ªè¿æ¥: "SQL/selfjoin"
#     - åˆ†ç»„èšåˆ: "SQL/groupby"
#     - ç¼ºå¤±å€¼å¤„ç†: "SQL/null"
#     - æ—¶é—´å¤„ç†: "SQL/time"
    
#   ğŸ‘‰æœºå™¨å­¦ä¹ ğŸ‘¨â€ğŸ’»: 
#     - æœ€å¤§ä¼¼ç„¶ä¼°è®¡: "ML/MLE"
#     - æ¢¯åº¦ä¸‹é™: "ML/gradient_descent"
#     - æ„ŸçŸ¥æœº: "ML/Perceptron"
#     - çº¿æ€§å›å½’: "ML/Linear_Regression"
#     - é€»è¾‘å›å½’: "ML/Logistic_regression"
#     - æ”¯æŒå‘é‡æœº: "ML/SVM"
#     - æœ´ç´ è´å¶æ–¯: "ML/Naive_Bayes"
#     - Kè¿‘é‚»: "ML/KNN"
#     - å†³ç­–æ ‘: "ML/Decision_Tree"
#     - éšæœºæ£®æ—: "ML/Random_Forest"
#     - Adaboost: "ML/Adaboost"
#     - GBDT: "ML/GBDT"
#     - XGBoost: "ML/XGBoost"
#     - k-means: "ML/kmeans"
#     - DBSCAN: "ML/DBSCAN"
#     - PCA: "ML/pca"
  
# #     - çº¿æ€§ç®—æ³•é¢ç»: "https://ex661wn4s4.feishu.cn/docx/YffKdkTLlo9772xHPMFc0sAWnbc"
# #     - æ ‘å‹ç®—æ³•é¢ç»: "https://ex661wn4s4.feishu.cn/docx/IypTdEjX6ojAp1xtJx3cQVyBnub"
    
  ğŸ‘‰å…è´¹èµ„æºğŸ‘¨â€ğŸ«: 
    - ä¼˜è´¨æ•°æ®æº: "datasource"
    - æ•°å­¦ç»Ÿè®¡: "https://zg104.github.io/DSCrashCourse#math--stats-%E6%95%B0%E5%AD%A6%E7%BB%9F%E8%AE%A1"
#    - SQLç¬”è®°: "https://docs.qq.com/doc/DRU5Pa0pManNvSXJH"
    - SQLåˆ·é¢˜: "https://docs.qq.com/sheet/DRUtTaE5wUHVLcVNN?tab=BB08J2"
#    - HiveQL: "HiveQLSparQL"
#    - Python: "https://zg104.github.io/DSCrashCourse#python"
#    - Numpy: "numpy"
 #   - Pandasè®­ç»ƒ: "Pandas"
    - ABå®éªŒ: "https://ex661wn4s4.feishu.cn/docx/QSeRdCR0BovRkrxOvb4ctyk0nfc"
    - R: "https://zg104.github.io/DSCrashCourse#r%E8%AF%AD%E8%A8%80"
    - Git: "https://zg104.github.io/DSCrashCourse#git"
    - Pandas: "https://ex661wn4s4.feishu.cn/docx/doxcnYhnPWtZBw9ceJZGG0wsQTf"
#    - Pandas_profiling: "pandas_profiling"
    
#  ğŸ‘‰é²¸æå°ç­è¯¾ğŸ‹: "https://mp.weixin.qq.com/s/5G9XOQbn-CqEWMyKMr8TTQ"
  ğŸ‘‰å¯»æ‰¾é²¸é²¸ğŸ‘€:
    - å°çº¢ä¹¦ğŸ“•: "https://www.xiaohongshu.com/user/profile/6180a092000000001f03501c?xhsshare=CopyLink&appuid=6180a092000000001f03501c&apptime=1651851000"
    - å…¬ä¼—å·ğŸ“—: "https://mp.weixin.qq.com/s/AtTq5vS5dkraJ7WeX3MqSw"
    - GithubğŸ–¤: "https://github.com/datoujinggzj"
#    - Giteeâ¤ï¸: "https://gitee.com/gzjzg/"
    - LeetCodeğŸ’¯: "https://leetcode-cn.com/u/zg104/"
    - bilibiliğŸ’«: "https://space.bilibili.com/497463853/channel/series"
#    - YouTubeğŸ“€: "https://www.youtube.com/channel/UCgieDnZI7JWiZsGpKrhDMgg"
#    - LinkedInâš™ï¸: "https://www.linkedin.com/in/zg104"
    - å…¨æ°‘Kæ­ŒğŸµ: "https://node.kg.qq.com/personal?uid=66999d87202a3e893c&stay=1"
# #   - æœºå™¨å­¦ä¹ ç®—æ³•æ€»ç»“: 'ml'
#     - çº¿æ€§å›å½’: "Linear_regression"
#     - é€»è¾‘å›å½’: "Logistic_regression"
#     - æœ´ç´ è´å¶æ–¯: "Naive_bayes"
#     - æ”¯æŒå‘é‡æœº: "SVM"
#     - kè¿‘é‚»: "KNN_tutorial"
#     - Kå¹³å‡: "kmeans"
#     - å†³ç­–æ ‘: "desciontree"
#     - æå‡ç®—æ³•: "boost"
#     - EMç®—æ³•&åº”ç”¨: "em"
#     - éšé©¬å°”ç§‘å¤«æ¨¡å‹: "HMM"
#     - è‡ªç¼–ç å™¨: 'AE'
#     - å·ç§¯å˜åˆ†è‡ªç¼–ç å™¨: 'Conv_VAE'

#     - åŸºäº LSTM çš„è®¾å¤‡å¥åº·è¯„ä¼°ä¸å‰©ä½™å¯¿é¢é¢„æµ‹çš„ç ”ç©¶: 'hpm'
#     - åŸºäºç¥ç»ç½‘ç»œæ¨¡å‹çš„æœºé˜Ÿå¯é æ€§æ•…éšœæŠ¥å‘Šåˆ†æ: 'relia'
#     - ç™Œç—‡å†å…¥é™¢ç‡é¢„æµ‹: "Readmission_prediction"
#     - å®‰å…¨é©¾é©¶é¢„æµ‹: "Safe_Driver_Prediction"
#     - å®¢æˆ·ç”»åƒ&å›è´­é¢„æµ‹: 'xgb'
#     - åŸºäºXGBoostçš„å›è´­é¢„æµ‹: 'kaijie_project'
#     - äº§èƒ½é¢„æµ‹: 'capacity_prediction'
#     - COVID-19åˆ†æé¢„æµ‹: "covid"
#     - ç»ç’ƒç¢ç‰‡è¯†åˆ«: "glass"
#     - å›¾åƒè¯†åˆ«: "deeplearning"
#     - å®‰å…¨é©¾é©¶é¢„æµ‹: "Safe_Driver_Prediction"
#     - KNNç®—æ³•åœ¨Irisä¸Šçš„åº”ç”¨: 'KNN'
#   é‡åŒ–:
#     - é‡åŒ–ä¹‹è·¯ï¼ˆä¸€ï¼‰: "Quant1"
#     - é‡åŒ–ä¹‹è·¯ï¼ˆäºŒï¼‰: "Quant2"
#     - AFML é‡‘èæ•°æ®ç»“æ„: "AFML_structure"
#     - AFML ä¸ºé‡‘èæ•°æ®æ‰“æ ‡ç­¾: "AFML_label"
#     - AFML å…ƒæ ‡ç­¾: "stack_meta"
#     - AFML æŠ½æ ·æƒé‡: "AFML_Sample_Weights"
#     - AFML åˆ†æ•°å·®åˆ†: "AFML_fdf"
#     - Tushare: "tushare"
#     - What Makes An Asset Useful: "wmaau"
#     - èµ„é‡‘æµå…¥æµå‡ºé¢„æµ‹ï¼ˆä¸Šï¼‰: 'eda1'
#     - èµ„é‡‘æµå…¥æµå‡ºé¢„æµ‹ï¼ˆä¸‹ï¼‰: 'eda2'
#     - è‚¡ä»·é¢„æµ‹: "Project"


  #Resources:
  # - Github: "https://github.com/zg104"
  # - çŸ¥ä¹: "https://www.zhihu.com/people/gao-zi-jing-98"
  # - LinkedIn: "https://www.linkedin.com/in/zg104/"
  # - Medium: "https://medium.com/@zg104"
 

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "image/whale_logo.png"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: image/selfpic.jpg


# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "2328247224@qq.com"
  facebook: whaleg123
  github: datoujinggzj
#   twitter: Zijing39896593
  rss: false
#  weixin: datoujinggzj
#  reddit: yourname
  linkedin: zg104
#  xing: yourname
  stackoverflow: "19072279/studywhale"
#  snapchat: deanat78
#  instagram: deanat78
  youtube: channel/UCgieDnZI7JWiZsGpKrhDMgg
#  spotify: yourname
  telephone: 18616531215
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
#   twitter: true
#   facebook: true
  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer

# Create a "tags" index page and make tags on each post clickable
#link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
#excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#F5F5F5"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# è§£é”èƒŒæ™¯
navbar-img: "/assets/img/bgimage.png"
footer-img: "/assets/img/bgimage.png"
page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: "UA-173057260-1"

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
disqus: "whalysis"
comments: true

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: "100026263117094"

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository", "branch", and "endpoint".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
#  reCaptcha:
#    siteKey  : # Use your own site key, you need to apply for one on Google
#    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
#title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
